// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImageFiles(arg1:string):Promise<Array<string>>;

export function SelectDirectory():Promise<string>;
