// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileBytes(arg1) {
  return window['go']['viewer']['ImageViewerService']['GetFileBytes'](arg1);
}

export function GetFileBytesRange(arg1, arg2, arg3) {
  return window['go']['viewer']['ImageViewerService']['GetFileBytesRange'](arg1, arg2, arg3);
}

export function GetFileSize(arg1) {
  return window['go']['viewer']['ImageViewerService']['GetFileSize'](arg1);
}

export function GetImageBase64(arg1) {
  return window['go']['viewer']['ImageViewerService']['GetImageBase64'](arg1);
}

export function GetImageFiles(arg1) {
  return window['go']['viewer']['ImageViewerService']['GetImageFiles'](arg1);
}

export function SelectDirectory() {
  return window['go']['viewer']['ImageViewerService']['SelectDirectory']();
}
