// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageFiles(arg1) {
  return window['go']['viewer']['ImageViewerService']['GetImageFiles'](arg1);
}

export function SelectDirectory() {
  return window['go']['viewer']['ImageViewerService']['SelectDirectory']();
}
